# Generated by Django 6.0.5 on 2026-05-30 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('electrico', 'Electrico'), ('mecanico', 'Mecanico'), ('hidraulico', 'Hidraulico'), ('neumatico', 'Neumatico'), ('electronico', 'Electronico')], max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('ubicacion', models.CharField(max_length=200)),
                ('fecha_de_anquisicion', models.DateField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
